name: ${project.name}
version: ${project.version}-b${env.TRAVIS_BUILD_NUMBER}
description: ${project.description}
authors: [cereal, Sleaker, mung3r, ShortFox]
website: ${project.url}
api-version: 1.21

main: ${mainClass}
load: startup

commands:
  vault-info:
    description: Displays information about Vault 
    usage: |
           /vault-info - Displays Vault information
    permission: vault.admin
  vault-convert:
    description: Converts all data from one economy to another
    usage: |
           /vault-convert [economy1] [economy2] - Converts data from [economy1] to [economy2]
    permission: vault.admin

permissions:
  vault.admin:
    description: Allows access to Vault administrative commands.
    default: op
